#!/bin/bash
TMPFILE=$(mktemp)

ps aux | sed -n 's/.*vvlp \([0-9]\{1,\}\)/\1/p' | sort -r | tee $TMPFILE

stty raw opost -echo && 
while read -u 3 port; do
  echo "try with port $port";
  ncat 127.1 $port;
  echo "connection to port $port closed";
  sleep 1;
done 3<$TMPFILE

rm $TMPFILE
